server.port: 8888
spring.application.name: gateway
# nacos配置
spring.cloud.nacos.config.server-addr: moon.crabapples.cn:8848
spring.cloud.nacos.config.namespace: a01
spring.cloud.nacos.discovery.namespace: a01
spring.cloud.nacos.config.file-extension: yaml
# 路由配置
spring.cloud.gateway:git
  # 路由网关配置(数组)
  routes:
    # 路由标识，自定义，唯一即可
    - id: consumer
      # 路由的目标地址 http是固定地址
      #      uri: http://192.168.3.2:6666
      # 路由的目标地址 lb是负载均衡，后面是服务名称
      uri: lb://consumer
      # 路由断言，也就是判断请求是否符合路由规则的条件
      predicates:
        # 按照路径配置，只要符合以/api/a开头的就会被路由到这里
        - Path=/api/consumer/**
      filters:
        - AddRequestHeader=User,crabapples
  default-filters:
    - AddRequestHeader=User,crabapples
