# eureka端口
server.port: 6666
# eureka的服务名称(即在注册中心里显示的名字)
spring.application.name: provider
# eureka的地址信息
eureka.client.service-url:
  defaultZone:
    http://192.168.3.2:20001/eureka
# nacos的地址信息
spring.cloud.nacos.server-addr: 192.168.3.2:8848
# 配置实例集群
spring.cloud.nacos.discovery.cluster-name: home
# 配置命名空间 home
spring.cloud.nacos.discovery.namespace: eb99b32b-ed5c-48a5-88df-0857f78b980c
# 配置是否为临时实例(默认为true)
spring.cloud.nacos.discovery.ephemeral: false
