# 端口
server.port: 6666
# 修改负载均衡策略(只针对某一个微服务)
# 服务名称.ribbon.NFLoadBalancerRuleClassName: 策略
#provider.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
provider.ribbon.NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
# 开启饥饿加载
#ribbon.eager-load.enabled: true
# 指定需要饥饿加载的服务名称
#ribbon.eager-load.clients: provider
