# eureka端口
server.port: 6668
# eureka的服务名称(即在注册中心里显示的名字)
spring.application.name: consumer
# eureka的地址信息
eureka.client.service-url:
  defaultZone:
    http://192.168.3.4:20001/eureka
# 修改负载均衡策略(只针对某一个微服务)
# 服务名称.ribbon.NFLoadBalancerRuleClassName: 策略
provider.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
# 开启饥饿加载
#ribbon.eager-load.enabled: true
# 指定需要饥饿加载的服务名称
#ribbon.eager-load.clients: provider
